name = "MLinJulia"
uuid = "1830c4c8-ad99-4928-96e4-58cd0b7ef8c1"
authors = ["Daniel Regado <danielregado@gmail.com>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NVTX = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
Underscores = "d9a01c3f-67ce-4d8c-9b55-35f6e4050bb1"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"
