name = "MLinJulia"
uuid = "1830c4c8-ad99-4928-96e4-58cd0b7ef8c1"
authors = ["Daniel Regado <danielregado@gmail.com>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"
